version: "3"
services:
  postgresql:
    image: "bitnami/postgresql:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_PASSWORD=password123
      - POSTGRESQL_DATABASE=readcommend
